### ISSUE TITLE
Xunit tests not working in VS for .Net Framework projects after upgrading to 2.4.2

### ISSUE THREAD

**Issue by farlop** [xunit/visualstudio.xunit#355] opened 2022-12-01 09:49 UTC
I'm using VS 17.4.2 in Spanish

Steps to reproduce:

1. Create xunit project using VS template (targeting .net 7.0, for example). This includes **xunit.runner.visualstudio 2.4.5** package
2. Run tests -> OK
3. Change TargetFramework to **net472**. Some additional steps:
    - Remove nodes `Nullable `and `ImplicitUsings `in .csproj
    - Remove file `Usings.cs`
    - Add `using Xunit;` to UnitTest1.cs
7. Run tests -> **Does not work (0 tests in message)**
8. Downgrade xunit.runner.visualstudio to version 2.4.1
9. Run tests -> Working again

I attach a repro project in final step. Just update xunit.runner.visualstudio to 2.4.2 or higher to see it failing

[Test472BugRepro.zip](https://github.com/xunit/visualstudio.xunit/files/10131206/Test472BugRepro.zip)

**Comment by trivalik** [comment] 2022-12-19 13:41
Maybe duplicate of https://github.com/xunit/visualstudio.xunit/issues/342 ?

**Comment by bradwilson** [comment] 2022-12-23 03:21
Closing as duplicate of 342.

**Closed by bradwilson** 2022-12-23 03:21 UTC
