### ISSUE TITLE
Console.CursorLeft causes ioexception 'the handle is invalid'

### ISSUE THREAD

**Issue by ileve** [xunit/visualstudio.xunit#244] opened 2020-10-25 19:52 UTC
When testing a net.core console application version 3.1 with xunit, I get a runtime exception when the following line of code is executed.
`int pos = Console.CursorLeft;`
The runtime exception i receive in the unit test is:
`Message: `
    `System.IO.IOException : The handle is invalid.`
  `Stack Trace: `
    `ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)`
    `Console.get_CursorLeft()`

The above runtime exception can be easily reproduced by creating a net.core 3.1 console application, then a xunit project and add a reference to the console application. Then write the following unit test.

```C#
        [Fact]
        public void testing_console()
        {
            Console.WriteLine("ffff");
            int pos = Console.CursorLeft;
            Assert.True(pos == 0);
        }
```
The peculiar thing is that if I right click the specific unit test and select `debug` instead of `run` then I receive no `ioexception`. The `ioexception` happens only when `run` is selected in the unit test.

nuget packages in xunit project:
xunit 2.4.0
xunit.runner.visualstudio 2.4.0
microsoft.net.test.sdk 16.2.0

Microsoft Visual Studio Community 2019 Version 16.4.0

**Comment by bradwilson** [comment] 2023-05-26 06:51
Sorry for the delay in getting to this issue.

I am able to reproduce this, albeit slightly differently, using .NET 6 and VS 2022. For me, it fails when both Run and Debug inside of Visual Studio, but succeeds when I use `dotnet test`. I believe the problem is that you don't have a console when VSTest is running your code inside of Visual Studio.

Either way, this is outside of our control. The issue can be raised with VSTest, but my guess is that they'll say that what you're trying to do is unsupported.

I'm closing this issue, since this is an external situation.

**Closed** 2023-05-26 06:51 UTC
Labels: status: External
