### ISSUE TITLE
XUnit can't skip theory tests correctly

### ISSUE THREAD

**Issue by Cosifne** [xunit/visualstudio.xunit#123] opened 2019-03-29 00:46 UTC
XUnit tests seems like can't skip test correctlly for theory tests.
Example:
```
using System;
using Xunit;
namespace XUnitTestProject2
{
    public class UnitTest1
    {
        [InlineData(true)]
        [InlineData(false, Skip = "Skip")]
        [InlineData(null, Skip = "Skip")]
        [Theory]
        public void Test1(bool? flag)
        {
            Assert.True(flag);
        }
    }
}
```
Screenshot by using command line:
![image](https://user-images.githubusercontent.com/24360909/55201558-bb353180-5180-11e9-86c7-b255100fe4fd.png)

Screenshot by using Visual Studio (15.9.6)
Turn off Source Based Test Discovery in Options panel first, then select the test in Test Explorer and run it by right click:
![image](https://user-images.githubusercontent.com/24360909/55201623-16ffba80-5181-11e9-9157-c459cfea8d7f.png)

**Comment by DerHulk** [comment] 2020-02-05 21:03
This bug still exists, will it be fixed in the near future?

**Comment by jzabroski** [comment] 2020-08-19 18:37
@bradwilson Duplicate of https://github.com/xunit/xunit/issues/1782

**Comment by bradwilson** [comment] 2023-05-26 07:11
Closing as duplicate.

**Closed by bradwilson** 2023-05-26 07:11 UTC
