### ISSUE TITLE
Dependency on xunit.runner.utility breaks xunit.runner.console

### ISSUE THREAD

**Issue by zeppelin37** [xunit/visualstudio.xunit#315] opened 2022-05-16 11:32 UTC
Hi,
my unit test project references both nuget packages "xunit.runner.visualstudio" V2.4.5 and "xunit.runner.console" V2.4.1.
Both ship with a xunit.runner.utility.net452.dll, but one with a version 2.4.1 and the other in 2.4.2. The files overwrite each other in the output directory.
What I don't understand, is:

- Why do you ship that dll at all? It is a separate nuget package, according to nuget.org 
- Why do you ship a "2.4.2-**pre**.22" version in a stable product?
- Where did you get the "pre.22" from? The latest available package on nuget.org is pre.12

**Comment by bradwilson** [comment] 2023-05-21 21:35
Two thoughts.

1. `xunit.runner.console` does not contain any libraries. It should not cause any dependencies when building:

   ![image](https://github.com/xunit/visualstudio.xunit/assets/16944/b83812da-5763-4400-b523-9795af73b27f)

   Adding `xunit.runner.visualstudio` of course results in the copy of several DLLs (including `xunit.runner.utility.net452.dll`, but there should be no conflicts here.

2. I can't provide a good answer as to why it was shipped that way. It looks like it came in with a PR from @ViktorHofer: https://github.com/xunit/visualstudio.xunit/pull/308. In my opinion, it should not have been merged with this prerelease dependency. It appears that it was done in a rush because of some issue caused by the `2.4.4` release and was perhaps not given enough attention as a result.

   As for where that build came from, this project has a [NuGet.Config](https://github.com/xunit/visualstudio.xunit/blob/main/NuGet.Config) that will pull prerelease builds from the CI build feed in MyGet. This is here for the convenience of testing prerelease builds before things get publicly pushed to NuGet. However, that doesn't excuse why this was done.

I'm not sure why you're getting a conflict. My suggestion would be to revert to an earlier runner (one of 2.4.1/2.4.2/2.4.3) and see if this resolves your problem.

**Comment by bradwilson** [comment] 2023-05-21 21:39
Please provide a full repro project if you can, since I cannot reproduce the problem as described.

**Comment by ViktorHofer** [comment] 2023-05-22 17:15
> I can't provide a good answer as to why it was shipped that way. It looks like it came in with a PR from @ViktorHofer: https://github.com/xunit/visualstudio.xunit/pull/308. In my opinion, it should not have been merged with this prerelease dependency. It appears that it was done in a rush because of some issue caused by the 2.4.4 release and was perhaps not given enough attention as a result.

Agreed on that we should update the version to stable here: https://github.com/xunit/visualstudio.xunit/blob/8dca8fefe3dad1e71ad23981b6cef3ab0e1e1ac4/Versions.props#L11.

Redistributing files like xunit.runner.utility or xunit.abstractions has caused double write issues in the past which we worked around ourselves, i.e. https://github.com/xunit/xunit/issues/1651. It might be good to re-evaluate the purpose of that process.

**Comment by bradwilson** [comment] 2023-05-22 20:55
> Agreed on that we should update the version to stable here:
> 
> https://github.com/xunit/visualstudio.xunit/blob/8dca8fefe3dad1e71ad23981b6cef3ab0e1e1ac4/Versions.props#L11

This is currently slated for a 2.5.0 prerelease of xunit.runner.visualstudio to coincide with a prerelease version of the core framework. When both reach RTM, the dependency will be an RTM dependency.

> Redistributing files like xunit.runner.utility or xunit.abstractions has caused double write issues in the past which we worked around ourselves, i.e. [xunit/xunit#1651](https://github.com/xunit/xunit/issues/1651). It might be good to re-evaluate the purpose of that process.

xunit.runner.utility and xunit.abstractions are needed on both sides of the app domain when using app domains in .NET Framework, so they need to be available in a predictable location on disk to be shared for both sides, so that the types are compatible when proxied.

**Comment by bradwilson** [comment] 2023-05-22 21:02
Example of the IL merge in v3:

Tasks:

https://github.com/xunit/xunit/blob/83fd34371733d26b6240c4e5abd2590dd712f76c/src/Directory.Build.targets#L37-L84

Opting in (note that `xunit.abstractions` is excluded):

https://github.com/xunit/xunit/blob/83fd34371733d26b6240c4e5abd2590dd712f76c/src/xunit.v3.runner.console/xunit.v3.runner.console.csproj

**Comment by bradwilson** [comment] 2023-07-26 05:43
Closing this as the prerelease has been resolved in 2.5.0 (and RTM versions of `xunit.runner.visualstudio` will stick with RTM versions of `xunit.runner.utility` moving forward). The other issue regarding conflict was not reproducible. If you can provide a repro with 2.5.0, please open a new issue. Thanks!

**Closed by bradwilson** 2023-07-26 05:43 UTC
Labels: status: Waiting for Repro/Response
